# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tic-Tac-Toe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import random


class Ui_MainWindow(QtWidgets.QMainWindow):
    userChoice,cpuChoice = "",""
    gameGrid =None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 120, 471, 461))
        self.frame.setStyleSheet("background-color: rgb(85, 170, 255); font: 36pt \"Lucida Calligraphy\";")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 40, 111, 111))
        self.pushButton.setStyleSheet("background-color: rgb(194, 221, 255);font: 36pt \"Lucida Calligraphy\";")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 40, 111, 111))
        self.pushButton_2.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 40, 111, 111))
        self.pushButton_3.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 180, 111, 111))
        self.pushButton_4.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 180, 111, 111))
        self.pushButton_5.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 180, 111, 111))
        self.pushButton_6.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 320, 111, 111))
        self.pushButton_7.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 320, 111, 111))
        self.pushButton_8.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(330, 320, 111, 111))
        self.pushButton_9.setStyleSheet("background-color: rgb(194, 221, 255); font: 36pt \"Lucida Calligraphy\";")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(190, 40, 601, 81))
        self.plainTextEdit.setStyleSheet("font: 36pt \"Lucida Calligraphy\";\n"
"text-decoration: underline;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 580, 201, 71))
        self.label.setStyleSheet("font: 20pt \"Playbill\";")
        self.label.setObjectName("label")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 590, 111, 51))
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.pushButton_10.setObjectName("pushButton_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Tic Tac Toe Game"))
        self.label.setText(_translate("MainWindow", "This is two player game"))
        self.pushButton_10.setText(_translate("MainWindow", "Start"))
        self.initEvents()

    def initEvents(self):
        self.gameGrid = [self.pushButton,self.pushButton_2,self.pushButton_3,self.pushButton_4,self.pushButton_5,self.pushButton_6,self.pushButton_7,self.pushButton_8,self.pushButton_9]
        self.pushButton_10.clicked.connect(self.startGame)
        for btn in self.gameGrid:
            btn.clicked.connect(self.userMove)
    def startGame(self):
        self.userChoice = 'X'
        self.cpuChoice = '0'

    def userMove(self):
        print(self.userChoice)
        btn = self.sender()
        btn.setText(self.userChoice)
        btn.setDisabled(True)
        self.check_winner(self.userChoice)
        self.cpuMove()
    def cpuMove(self):
        emptyButtons = [btn for btn in self.gameGrid if btn.text() == ""]
        if emptyButtons:
            btn = random.choice(emptyButtons)
            btn.setText(self.cpuChoice)

            btn.setDisabled(True)
            self.check_winner(self.cpuChoice)

    def check_winner(self,player):
        winning_combinations = [[self.pushButton,self.pushButton_2,self.pushButton_3],[self.pushButton_4,self.pushButton_5,self.pushButton_6],[self.pushButton_7,self.pushButton_8,self.pushButton_9],[self.pushButton,self.pushButton_4,self.pushButton_7],[self.pushButton_2,self.pushButton_5,self.pushButton_8],[self.pushButton_3,self.pushButton_6,self.pushButton_9],[self.pushButton,self.pushButton_5,self.pushButton_9],[self.pushButton_3,self.pushButton_5,self.pushButton_7],]

        for combo in winning_combinations:
            combo_match = True
            for btn in combo:
                if btn.text() != player:
                    combo_match = False
                    break
            if combo_match:
                self.label.setText(player+" "+"wins..!")
                self.disableButtons()
                return

        all_filled = True
        for btn in self.gameGrid:
            if btn.text() == "":
                all_filled = False
                break
        if all_filled:
            self.label.setText("It's Tie!")
            self.disableButtons()
            return
    def disableButtons(self):
        for btn in self.gameGrid:
            btn.setDisabled(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



#pyuic5 -x file_name.ui -o file_name.py